# This is a basic workflow to help you get started with Actions
# Simple workflow for deploying static content to GitHub Pages

name: Fetch market data, process it and make available to public

on:
    # Runs on pushes targeting the default branch
    #push:
    #    branches: ['main']
    schedule:
        - cron: '30 1 * * 1-5' # 7:30 AM IST (1:00 AM UTC) Monday to Friday

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    # Fetch and extract job
    fetch_and_extract:
        runs-on: ubuntu-latest
        #strategy:
        #matrix:
        #node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  #node-version: ${{ matrix.node-version }}
                  node-version: 20
                  # cache: 'npm'

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            - name: Fetch data, extract and write compressed CSV data with NodeJs
              #run: npm ci
              #run: npm run build --if-present
              # run: npm test
              run: node src/upstoxMasterData.js

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './public'

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: fetch_and_extract # the job mentioned above
        steps:
            #- name: Checkout
            #  uses: actions/checkout@v4
            #- name: Setup Pages
            #  uses: actions/configure-pages@v5
            #- name: Upload artifact
            #  uses: actions/upload-pages-artifact@v3
            #  with:
            #    path: './public'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
